# Project information
site_name: "PESTO : ProcESsing facTOry"
site_url: "https://airbusdefenceandspace.github.io/pesto"
site_author: Airbus Defence and Space - Processing Factory Team
site_description: Documentation for the PESTO toolbox

# Repository
repo_name: AirbusDefenceAndSpace/pesto
repo_url: https://github.com/AirbusDefenceAndSpace/pesto
edit_uri: ""


use_directory_urls: false

# Copyright
copyright: Copyright &copy; 2023 Airbus Defence and Space

# Configuration
theme:
    name: material
    highlightjs: true

# Plugins
plugins:
  - search
  - mermaid2

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
#  - https://unpkg.com/mermaid@8.0.0/dist/mermaid.min.js
  - js/mermaid.min.js

# Page tree
nav:
  - About: about.md
  - Get started: get_started.md
  - Package an Algorithm:
      - Create a PESTO project: package_pesto_project.md
      - Project configuration: package_configuration.md
      - Build the Docker image: package_docker_image.md
      - Test the Docker image: package_test.md
  - Run the Algorithm:
      - Run the packaged algorithm: deploy_run_docker_image.md
      - Web-service: deploy_web_service.md
  - PESTO commands:
      - init:  pesto_init.md
      - schemagen: pesto_schemagen.md
      - build: pesto_build.md
      - test:  pesto_test.md
      - run: pesto_run.md
      - list: pesto_list.md
  - Tutorial:
      - Deploying a pytorch model: tutorial_pytorch.md
  - PESTO in details:
      - Conventions: details_conventions.md
      - Design : details_design.md
      - Cookbook: details_cookbook.md
      - Troubleshooting: details_troubleshooting.md
